e_dfsclass<-function(explaining=0){

  if(explaining==0) {
  cat("  ", '\n')
  cat("\033[1;32m## Statistics for PA and AI dataset ----------- \033[0m", '\n')
  cat("  Dataset ---- ", '\n')
  cat("  df00_id_brand_conv ", '\n')
  cat("  df01_study_exhaust ", '\n')
  cat("  df02_gdp_local_tax ", '\n')
  cat("  df03_emotion_labor ", '\n')
  cat("  df04_consumption_gdp ", '\n')
  cat("  df05_titanic ", '\n')
  cat("  df06_mdis_house_finance18 ", '\n')
  cat("  df07_caffe ", '\n')
  cat("  df08_industry17 ", '\n')
  cat("  df09_travel22 ", '\n')
  cat("  df10_housing_status22 ", '\n')
  cat("  df11_mdis_donation18 ", '\n')
  cat("  df12_survey_donation ", '\n')
  cat("  df13_final_exam ", '\n')
  cat("  df14_final_exam ", '\n')
  cat("  df15_suwon ", '\n')
  cat("  df16_corp2021 ", '\n')
  cat("  df17_OLS ", '\n')
  cat("  df18_anova ", '\n')
  cat("  df19_chisq ", '\n')
  cat("  df20_crispy ", '\n')
  cat("  df21_foot ", '\n')
  cat("  df22_path ", '\n')
  cat("  df23_law ", '\n')
  cat("   ", '\n')
  } }

