e_dfsclass<-function(explaining=0){

  if(explaining==0) {
  cat("  ", '\n')
  cat("\033[1;32m## Statistics for PA and AI dataset ----------- \033[0m", '\n')
  cat("\033[1;32m  Dataset ---- \033[0m", '\n')
  cat("  df1 (df01_id_brand_conv) ", '\n')
  cat("  df2 (df02_study_exhaust)  ", '\n')
  cat("  df3 (df03_gdp_local_tax) ", '\n')
  cat("  df4 (df04_consumption_gdp) ", '\n')
  cat("  df5 (df05_titanic) ", '\n')
  cat("  df6 (df06_mdis_house_finance18) ", '\n')
  cat("  df7 (df07_caffe) ", '\n')
  cat("  df8 (df08_industry17) ", '\n')
  cat("  df9 (df09_travel22) ", '\n')
  cat("  df10 (df10_housing_status22) ", '\n')
  cat("  df11 (df11_mdis_donation18) ", '\n')
  cat("  df12 (df12_survey_donation) ", '\n')
  cat("  df13 (df13_final_exam) ", '\n')
  cat("  df14 (df14_final_exam) ", '\n')
  cat("  df15_suwon ", '\n')
  cat("  df16 (df16_corp2021) ", '\n')
  cat("  df17 (df17_OLS) ", '\n')
  cat("  df18_anova ", '\n')
  cat("  df19_chisq ", '\n')
  cat("  df20_crispy ", '\n')
  cat("  df21_foot ", '\n')
  cat("  df22_path ", '\n')
  cat("  df23_law ", '\n')
  cat("   ", '\n')
  } }

