e_dfsclass<-function(explaining=0){

  if(explaining==0) {
  cat("  ", '\n')
  cat("\033[1;32m## Statistics for PA and AI dataset ----------- \033[0m", '\n')
  cat("\033[1;32m  Dataset ---- \033[0m", '\n')
  cat("  df1 (id_brand_conv) ", '\n')
  cat("  df2 (study_exhaust)  ", '\n')
  cat("  df3 (gdp_local_tax) ", '\n')
  cat("  df4 (consumption_gdp) ", '\n')
  cat("  df5 (titanic) ", '\n')
  cat("  df6 (mdis_house_finance18) ", '\n')
  cat("  df7 (caffe) ", '\n')
  cat("  df8 (industry17) ", '\n')
  cat("  df9 (travel22) ", '\n')
  cat("  df10 (housing_status22) ", '\n')
  cat("  df11 (mdis_donation18) ", '\n')
  cat("  df12 (survey_donation) ", '\n')
  cat("  df13 (final_exam1) ", '\n')
  cat("  df14 (final_exam2) ", '\n')
  cat("  df15 (suwon) ", '\n')
  cat("  df16 (corp2021) ", '\n')
  cat("  df17 (OLS_봄여름가을겨울) ", '\n')
  cat("  df18 (anova) ", '\n')
  cat("  df19 (chisq) ", '\n')
  cat("  df20 (crispy) ", '\n')
  cat("  df21 (foot) ", '\n')
  cat("  df22 (path) ", '\n')
  cat("  df23 (law) ", '\n')
  cat("   ", '\n')
  } }

